name = "wokspec-dilu"
compatibility_date = "2026-02-20"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".deploy"

[vars]
NEXT_PUBLIC_BASE_URL = "https://dilu.wokspec.org"

[[kv_namespaces]]
binding = "WAITLIST_KV"
id = "97ea97b2c7854e94adc79f9dfd965c68"
